title: Darren Yao's website
description: Hi, I'm Darren, currently a senior at Carlmont High School interested in mathematics and computer science.
permalink: ':title/'
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://darrenyao.com/" # the base hostname & protocol for your site, e.g. http://example.com
site-twitter: #if your site has a twitter account, enter it here

# Author Settings
author: Darren Yao # add your name
author-img: websitepfp.png # add your photo
about-author: Hi, I'm Darren, currently a senior at Carlmont High School interested in mathematics and computer science. # add description
social-twitter: DarrenYao5
social-facebook: # add your Facebook handle
social-github: darren-yao # add your Github handle
social-linkedin: darren-yao # add your Linkedin handle
social-email: darren.yao@gmail.com # add your Email address

# Tracker
analytics: UA-168722146-1

# Build Settings
markdown: kramdown
kramdown:
    math_engine: mathjax
plugins:
  - jekyll-sitemap
  - jekyll-paginate
  - jemoji
  - jekyll-redirect-from

paginate: 8
paginate_path: "/page/:num"

exclude: ["node_modules", "gulpfile.js", "package.json", "yarn.lock"]
